apiVersion: v1
kind: Service
metadata:
  namespace: bookshop
  name: bff
spec:
  selector:
    app: bff
  ports:
  - protocol: TCP
    name: tcp
    port: 4000
    targetPort: 4000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bookshop
  name: bff
  labels:
    app: bff
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
      version: v1
  template:
    metadata:
      labels:
        app: bff
        version: v1
    spec:
      containers:
      - name: bff
        image: keitamido/bookshop-bff:0.1
        env:
        - name: CATALOGUE_CLIENT_URI
          value: "catalogue:50051"
        ports:
        - containerPort: 4000